# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('dispositivo', models.CharField(max_length=25)),
                ('marca', models.CharField(blank=True, max_length=25)),
                ('modelo', models.CharField(blank=True, max_length=25)),
                ('num_serie', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de asignación: ')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Usuario')),
            ],
        ),
    ]
