# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('dispositivos', '0002_dispositivos_fecha_instalacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('num_serie', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('dispositivo', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('modelo', models.CharField(max_length=25)),
                ('fecha_instalacion', models.DateTimeField(default=datetime.datetime(2018, 1, 10, 15, 3, 48, 317436), verbose_name='Fecha de asignación: ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Dispositivos',
        ),
    ]
