# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_auto_20180110_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_instalacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 12, 6, 12, 525398), verbose_name='Fecha de asignación: '),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
