# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_auto_20180111_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_instalacion',
            field=models.DateTimeField(default=datetime.date(2018, 1, 11), verbose_name='Fecha de asignación: '),
        ),
    ]
