# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0006_auto_20180111_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_instalacion',
            field=models.DateField(default=datetime.date(2018, 1, 12), verbose_name='Fecha de asignación: '),
        ),
    ]
