# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20180112_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fuera_convenio',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
