# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20180112_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fuera_convenio',
            field=models.NullBooleanField(default=0),
        ),
    ]
