# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20180113_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fuera_convenio',
            field=models.NullBooleanField(),
        ),
    ]
