# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20180113_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fuera_convenio',
            field=models.NullBooleanField(choices=[(None, 'OFF'), (True, 'YES'), (False, 'NO')]),
        ),
    ]
