# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20180113_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fuera_convenio',
            field=models.BooleanField(default=False),
        ),
    ]
